
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-ASSIGNDIVIDE ASSIGNMINUS ASSIGNPLUS ASSIGNTIMES BREAK CONTINUE ELSE EQ EYE FLOATNUMBER FOR GEQ ID IF INTNUMBER LEQ MDIVIDE MMINUS MPLUS MTIMES NEQ ONES PRINT RETURN STRING WHILE ZEROSexpression : expression '+' expression\n                  | expression '-' expression\n                  | INTNUMBER"
    
_lr_action_items = {'INTNUMBER':([0,3,4,],[2,2,2,]),'$end':([1,2,5,6,],[0,-3,-1,-2,]),'+':([1,2,5,6,],[3,-3,-1,-2,]),'-':([1,2,5,6,],[4,-3,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression + expression','expression',3,'p_binary_operators','Mparser.py',24),
  ('expression -> expression - expression','expression',3,'p_binary_operators','Mparser.py',25),
  ('expression -> INTNUMBER','expression',1,'p_binary_operators','Mparser.py',26),
]
